name: Deploy Hugo site to Github Pages

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - "LICENSE"
      - "README.md"

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  fqdn: https://iharshad.github.io

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo binaries
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.97.0'
          extended: true

      # - name: Update domain name in config file
      #   uses: jacobtomlinson/gha-find-replace@v2
      #   with:
      #     find: 'baseURL: "/"'
      #     replace: 'baseURL: "https://iharshad.github.io"'
      #     include: 'config.yaml' # Will match config.yaml file only

      - name: Build static site
        run: |
          hugo \
            --baseURL $fqdn \
            --cleanDestinationDir \
            --destination="dist" \
            --enableGitInfo=true \
            --templateMetrics \
            --templateMetricsHints \
            --minify

      - name: Deploy static site
        uses: peaceiris/actions-gh-pages@v3.9.2
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          # cname: github.com
          github_token: ${{ secrets.GITHUB_TOKEN }} # token generated by Actions during execution
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          commit_message: ${{ github.sha }} ${{ github.event.head_commit.message }}
          publish_branch: gh-pages # set a branch name to use as GitHub Pages branch
          publish_dir: ./dist # a source directory to deploy to GitHub Pages
