name: Deploy Hugo site to Github Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - "LICENSE"
      - "README.md"

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  # Allows you to hit the API from anywhere to trigger workflow on all branchs
  # /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
  # https://stackoverflow.com/a/68148239
  workflow_dispatch:

  # For testing only
  repository_dispatch:

  
# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: write
#   pages: write
#   id-token: write

# Ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  BASE_URL: https://iharshad.github.io

jobs:
  build:
    runs-on: ubuntu-22.04

    outputs:
      date_info: ${{ steps.step3.outputs.date_info }}
      branch_info: ${{ steps.step3.outputs.branch_info }}
      commit_info: ${{ steps.step3.outputs.commit_info }}
      author_info: ${{ steps.step3.outputs.author_info }}
      message_info: ${{ steps.step3.outputs.message_info }}

    steps:
      - name: Set GHA runner TZ to IST
        id: step00
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Kolkata" # default = "UTC"

      - name: Checkout website code and theme
        id: step0
        uses: actions/checkout@v3.3.0
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: true
          # Fetch full history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Pull latest content
        id: step1
        uses: actions/checkout@v3.3.0
        with:
          repository: iHarshad/hugo-example-content
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          path: content

      - name: Setup Hugo binaries
        id: step2
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.97.0'
          extended: true

      # Use MD template - https://github.com/lmservas/hikari-x86_64/blob/afaa6ad0e5814ef46755e83a0c20b07696938c40/.github/workflows/update-readme.yml

      - name: Get website info
        id: step3
        run: |
          set -x
          bash --version
          commit_format=" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"

          echo "## Website Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Commit Details</summary>" >> $GITHUB_STEP_SUMMARY
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          # Working
          website_info=`git log --max-count=1 --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"`
          # Not Working
          # website_info=$(git log --max-count=1 --pretty=format:${commit_format})
          echo "${website_info}" >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line

          echo "## Theme Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          # Working
          cd themes/maverick
          theme_info=`git log --max-count=1 --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"`
          # Not Working
          # theme_info=`git log --max-count=1 --pretty=format:$commit_format`
          cd ../..
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Commit Details </summary>" >> $GITHUB_STEP_SUMMARY
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          echo "${theme_info}" >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line

          echo "## Content Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          # Working
          cd content
          content_info=`git log --max-count=1 --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"`
          # Not Working
          # content_info=`git log --max-count=1 --pretty=format:$commit_format`
          cd ..
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Commit Details</summary>" >> $GITHUB_STEP_SUMMARY
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          echo "${content_info}" >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line

      # - name: Update domain name in config file
      #   uses: jacobtomlinson/gha-find-replace@v2
      #   with:
      #     find: 'baseURL: "/"'
      #     replace: 'baseURL: "https://iharshad.github.io"'
      #     include: 'config.yaml' # Will match config.yaml file only

      - name: Build static site
        id: step4
        run: |
          hugo \
            --baseURL $BASE_URL \
            --cleanDestinationDir \
            --destination="dist" \
            --enableGitInfo=true \
            --templateMetrics \
            --templateMetricsHints \
            --minify \
            --gc

      - name: Create build archive
        run: |
          tar -czvf build.tar.gz dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build.tar.gz
          path: build.tar.gz
          if-no-files-found: warn
          retention-days: 5 # default 90 days

  test:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Set GHA runner TZ to IST
        id: step00
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Kolkata" # default = "UTC"

      - name: Download build.tar.gz artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: build.tar.gz

      - name: Extract artifact
        run: |
          tar -xzvf build.tar.gz

      - name: Test build files
        run: |
          echo -e "Testing"

      - name: Create dist archive
        run: |
          tar -czvf dist.tar.gz dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist.tar.gz
          path: dist.tar.gz
          if-no-files-found: warn
          retention-days: 5 # default 90 days

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Set GHA runner TZ to IST
        id: step00
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Kolkata" # default = "UTC"

      - name: Download dist.tar.gz artifact from test job
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist.tar.gz

      - name: Extract artifact
        run: |
          tar -xzvf dist.tar.gz

      - name: Deploy static site
        id: step5
        uses: peaceiris/actions-gh-pages@v3.9.2
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          # cname: mysite.com
          # token generated by Actions during execution
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
          # set a branch name to use as GitHub Pages branch
          publish_branch: gh-pages
          # a source directory to deploy to GitHub Pages
          publish_dir: ./dist
          # Overwrite existing files
          keep_files: false
          # Set custom Git username and email
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
